# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20161113_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='textQuestion',
            field=models.TextField(max_length=1000),
        ),
    ]
