# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20161113_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='normalQuestion',
            new_name='correct_question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='textQuestion',
            new_name='text_question',
        ),
    ]
