# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20161113_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_question',
            new_name='correct',
        ),
        migrations.AddField(
            model_name='question',
            name='name_question',
            field=models.CharField(default='void', max_length=50),
        ),
    ]
