# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20161114_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='questionid',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='timestart',
            new_name='time_start',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='userid',
            new_name='user_id',
        ),
    ]
