# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20161114_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='time_start',
            field=models.IntegerField(default=0),
        ),
    ]
