# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20161129_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='id',
            new_name='id_q',
        ),
    ]
